language: android

jdk:
 - oraclejdk7

before_install:
 - chmod +x gradlew

android:
  components:
    - build-tools-23.0.2
    - tools
    - android-23
    - extra-android-m2repository

script: ./gradlew assembleDebug

notifications:
  email: false

sudo: false
